typography_spectrum: 0.9179682515095919
color:
  brandStrength: 0.8113066002260894
  lightness: 0.8933733394369483
  saturation: 0.7128187329508364
  rhythmicContrast: 0.28817719500511885
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
opengraph:
  appId: '264326337293987'
  type: '264326337293987'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/27cc7433-958e-4ae8-9242-dc4b7d23310a.jpg
layout_spectrum: 0.3993369033560157
author:
  name: Jan Brouwer
  email: j.brouwerstedebouwer@gmail.com
name: Tour d'Europe langs nieuw gestichte steden in de late Middeleeuwen
title: Tour d'Europe
description: langs nieuw gestichte steden in de late Middeleeuwen
